language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-25
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

jdk:
  - openjdk8
